add_newline = false
command_timeout = 200
format = """[$conda$python$username$hostname$directory](bold cyan)$git_branch$git_status$character"""

[python]
format = '(\($virtualenv\) )($style)'
style  = 'bold fg:5'

[conda]
format = '[\($environment\) ]($style)'
style = "bold #FFFFFF"
ignore_base = false

[username]
format          = '[$user]($style)'
show_always     = true
detect_env_vars = []

[hostname]
format   = '[@$hostname] ($style)'
disabled = false
ssh_only = true

[character]
success_symbol = '[𝜓 ](bold #ff00ff)'
error_symbol = '[𝜓 ](bold #ff0000)'

[directory]
repo_root_style = "bold #ffaa00"
repo_root_format = ":[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
read_only_style = "bold #ff0000"
style = "bold #7a4000"
format = ":[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "on [$branch]($style) "
style = "italic #4488ff"

[git_status]
format     = '[$all_status]($style)'
style      = "#4488ff"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

